export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';

export const ADD_ACTIVITY_SLOT = 'app/MainPage/ADD_ACTIVITY_SLOT';
export const ADD_ACTIVITY_SLOT_SUCCESS =
  'app/MainPage/ADD_ACTIVITY_SLOT_SUCCESS';
export const ADD_ACTIVITY_SLOT_ERROR = 'app/MainPage/ADD_ACTIVITY_SLOT_ERROR';

export const LOAD_ACTIVITIES = 'app/MainPage/LOAD_ACTIVITIES';
export const LOAD_ACTIVITIES_SUCCESS = 'app/MainPage/LOAD_ACTIVITIES_SUCCESS';
export const LOAD_ACTIVITIES_ERROR = 'app/MainPage/LOAD_ACTIVITIES_ERROR';

export const LOAD_SCHEDULE = 'app/MainPage/LOAD_SCHEDULE';
export const LOAD_SCHEDULE_SUCCESS = 'app/MainPage/LOAD_SCHEDULE_SUCCESS';
export const LOAD_SCHEDULE_ERROR = 'app/MainPage/LOAD_SCHEDULE_ERROR';
